# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-09 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20180608_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_set', to='tickets.Question'),
        ),
    ]
