# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-30 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20180609_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '\u0412\u043e\u043f\u0440\u043e\u0441', 'verbose_name_plural': '\u0412\u043e\u043f\u0440\u043e\u0441\u044b'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': '\u0422\u0435\u043c\u0430', 'verbose_name_plural': '\u0422\u0435\u043c\u044b'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': '\u0411\u0438\u043b\u0435\u0442', 'verbose_name_plural': '\u0411\u0438\u043b\u0435\u0442\u044b'},
        ),
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tickets.Theme'),
        ),
    ]
