# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-30 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20180630_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_status',
            field=models.BooleanField(default=False, verbose_name='\u041f\u0440\u0430\u0432\u0438\u043b\u044c\u043d\u044b\u0439 \u043e\u0442\u0432\u0435\u0442'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=1000, verbose_name='\u0412\u0430\u0440\u0438\u0430\u043d\u0442 \u043e\u0442\u0432\u0435\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_set', to='tickets.Question', verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='tickets_img/', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=1000, verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '1'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], verbose_name='\u2116 \u0432\u043e\u043f\u0440\u043e\u0441\u0430'),
        ),
        migrations.AlterField(
            model_name='question',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tickets.Theme', verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0442\u0435\u043c\u044b'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tickets.Ticket', verbose_name='\u2116 \u0431\u0438\u043b\u0435\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=500, verbose_name='\u0422\u0435\u043c\u0430'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='drive_category',
            field=models.CharField(choices=[('A, B, M', 'A, B, M'), ('C \u0438 \u0414', 'C \u0438 \u0414')], max_length=500, verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u0432\u043e\u0436\u0434\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tick_number',
            field=models.IntegerField(verbose_name='\u2116 \u0431\u0438\u043b\u0435\u0442\u0430'),
        ),
    ]
