# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-03 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20180702_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_status',
            field=models.BooleanField(verbose_name='\u041f\u0440\u0430\u0432\u0438\u043b\u044c\u043d\u044b\u0439 \u043e\u0442\u0432\u0435\u0442'),
        ),
    ]
