# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-04 09:34
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20180703_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tip',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True, verbose_name='\u041f\u043e\u0434\u0441\u043a\u0430\u0437\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=1, verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441 \u2116'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tickets.Ticket', verbose_name='\u0411\u0438\u043b\u0435\u0442 \u2116'),
        ),
    ]
